import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import Navbar from '../components/Navbar.jsx';
import SubNavbar from '../components/SubNavbar.jsx';
import Footer from '../components/Footer.jsx';
import { useCart } from '../context/CartContext.jsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const SavedBuildsPage = () => {
    const [savedBuilds, setSavedBuilds] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const { addToCart } = useCart();
    const navigate = useNavigate();

    useEffect(() => {
        const fetchSavedBuilds = async () => {
            const userStr = localStorage.getItem('user');
            if (!userStr) {
                setIsLoading(false);
                return;
            }
            const user = JSON.parse(userStr);
            const userId = user.id || user._id;

            try {
                const response = await fetch(`http://localhost:4080/api/pc-builds/user/${userId}`);
                if (response.ok) {
                    const data = await response.json();
                    setSavedBuilds(data);
                }
            } catch (error) {
                console.error('Error fetching saved builds:', error);
            } finally {
                setIsLoading(false);
            }
        };

        fetchSavedBuilds();
    }, []);

    const handleDownloadPDF = (build) => {
        try {
            const doc = new jsPDF();

            // Header
            doc.setFontSize(22);
            doc.text("PC Configuration Report", 14, 20);

            doc.setFontSize(12);
            doc.setTextColor(100);
            doc.text(`Build Name: ${build.name}`, 14, 30);
            doc.text(`Date: ${build.created_at ? new Date(build.created_at).toLocaleDateString() : new Date().toLocaleDateString()}`, 14, 37);
            doc.text(`Total Price: ₹${build.total_price?.toLocaleString('en-IN') || '0'}`, 14, 44);

            // Components Table
            const tableColumn = ["Category", "Product Name", "Price"];
            const tableRows = [];

            if (build.items && Array.isArray(build.items)) {
                build.items.forEach(item => {
                    const productData = [
                        item.category_id?.replace('cat_', '').replace('_', ' ').toUpperCase() || 'GENERAL',
                        item.product_id?.name || 'N/A',
                        `₹${item.variant_id?.price?.toLocaleString('en-IN') || item.product_id?.price?.toLocaleString('en-IN') || '0'}`
                    ];
                    tableRows.push(productData);
                });
            }

            autoTable(doc, {
                startY: 55,
                head: [tableColumn],
                body: tableRows,
                theme: 'striped',
                headStyles: { fillColor: [234, 88, 12] }, // Orange-600 color
                margin: { top: 55 },
            });

            // Footer note
            const finalY = (doc.lastAutoTable?.finalY || 150) + 10;
            doc.setFontSize(10);
            doc.setTextColor(150);
            doc.text("Generated by PC Store Builder", 14, finalY);

            doc.save(`${build.name.replace(/\s+/g, '_')}_config.pdf`);
        } catch (error) {
            console.error('PDF Generation Error:', error);
            alert('Failed to generate PDF. Check console for details.');
        }
    };

    const handleAddToCart = (build) => {
        if (!build.items || build.items.length === 0) return;

        build.items.forEach(item => {
            if (item.product_id) {
                addToCart({
                    ...item.product_id,
                    id: item.product_id._id,
                    price: item.variant_id?.price || item.product_id.price || 0
                });
            }
        });
        alert(`All components from "${build.name}" added to cart!`);
    };

    const handleLoadBuild = (build) => {
        // Logic to load build into configurator could go here
        // For now, let's just navigate to configurator or alert
        alert('Load build functionality can be implemented by syncing with Configurator state.');
        navigate('/configurator');
    };

    return (
        <div className="min-h-screen bg-[#eef2f2] font-sans flex flex-col">
            <Navbar />
            <SubNavbar />

            <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 flex-1 w-full">
                <div className="flex justify-between items-end mb-10">
                    <div>
                        <h1 className="text-4xl font-black text-gray-900 tracking-tight uppercase">Your Saved Builds</h1>
                        <p className="text-gray-600 mt-2">Manage your custom PC configurations and quickly add them to cart.</p>
                    </div>
                    <button
                        onClick={() => navigate('/configurator')}
                        className="bg-orange-600 text-white px-6 py-3 rounded-lg font-black hover:bg-orange-700 transition-all shadow-lg shadow-orange-600/20"
                    >
                        + New Build
                    </button>
                </div>

                {isLoading ? (
                    <div className="flex justify-center items-center py-20">
                        <div className="w-12 h-12 border-4 border-orange-200 border-t-orange-600 rounded-full animate-spin"></div>
                    </div>
                ) : savedBuilds.length === 0 ? (
                    <div className="text-center py-20 bg-white rounded-2xl border border-dashed border-gray-300">
                        <p className="text-gray-500 text-lg">You haven't saved any builds yet.</p>
                        <button
                            onClick={() => navigate('/configurator')}
                            className="mt-4 text-orange-600 font-bold hover:underline"
                        >
                            Start building now →
                        </button>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {savedBuilds.map((build) => (
                            <div key={build._id} className="bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300 border border-gray-100 group">
                                <div className="p-6">
                                    <div className="flex justify-between items-start mb-4">
                                        <h3 className="text-xl font-black text-gray-900 truncate flex-1">{build.name}</h3>
                                        <span className="bg-gray-100 px-3 py-1 rounded-full text-xs font-black text-gray-500 whitespace-nowrap ml-2">
                                            {new Date(build.created_at).toLocaleDateString()}
                                        </span>
                                    </div>

                                    <div className="space-y-1 mb-6 h-28 overflow-y-auto custom-scrollbar">
                                        {build.items?.slice(0, 6).map((item, idx) => (
                                            <p key={idx} className="text-sm text-gray-500 flex items-center">
                                                <span className="w-1.5 h-1.5 bg-orange-600 rounded-full mr-2 flex-shrink-0"></span>
                                                <span className="truncate">{item.product_id?.name || 'Component'}</span>
                                            </p>
                                        ))}
                                        {build.items?.length > 6 && (
                                            <p className="text-xs text-gray-400 font-bold mt-1">
                                                + {build.items.length - 6} more components
                                            </p>
                                        )}
                                    </div>

                                    <div className="flex items-center justify-between pt-4 border-t border-gray-100">
                                        <div className="leading-tight">
                                            <p className="text-xs text-gray-400 font-bold uppercase">Total Price</p>
                                            <p className="text-2xl font-black text-orange-600">₹{build.total_price?.toLocaleString('en-IN')}</p>
                                        </div>
                                        <div className="flex space-x-2">
                                            <button
                                                onClick={() => handleDownloadPDF(build)}
                                                className="p-2 bg-gray-50 text-gray-600 rounded-lg hover:bg-gray-100 transition-colors"
                                                title="Download PDF"
                                            >
                                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                                </svg>
                                            </button>
                                            <button
                                                onClick={() => handleLoadBuild(build)}
                                                className="px-4 py-2 bg-black text-white rounded-lg font-bold hover:bg-gray-800 transition-colors"
                                            >
                                                Load
                                            </button>
                                        </div>
                                    </div>

                                    <button
                                        onClick={() => handleAddToCart(build)}
                                        className="w-full mt-4 bg-orange-600/10 text-orange-600 py-3 rounded-lg font-black hover:bg-orange-600 hover:text-white transition-all text-sm uppercase"
                                    >
                                        Add to Cart
                                    </button>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </main>

            <Footer />
        </div>
    );
};

export default SavedBuildsPage;
